version: 2
jobs:
  build:
    docker:
      - image: dlang2/dmd-circleci:2.087.1
    steps:
      - checkout
      - run: dub build
  test:
    docker:
      - image: dlang2/dmd-circleci:2.087.1
    steps:
      - checkout
      - run: dub test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
